version: '3'
services:
  frontend:
    build: ./ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:5000  # Environment variable for the backend URL

  backend:
    build: ./ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/ecommerce  # MongoDB connection string
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"  # Host port 27018 maps to container port 27017
    volumes:
      - mongo-data:/data/db  # Persistent data volume for MongoDB

volumes:
  mongo-data:  # Define the persistent data volume